[workspace]
channels = ["conda-forge"]
name = "legacy-converters"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
xarray = ">=2025.11.0"
numpy = ">=2.3.4,<3"
zarr = ">=3.1.3,<4"
xdggs = ">=0.4.0"
healpix-geo = ">=0.0.7"
dask = ">=2025.10.0,<2026"
distributed = ">=2025.10.0,<2026"
scipy = ">=1.16.3,<2"
pystac-client = ">=0.9.0,<0.10"
matplotlib = ">=3.10.7,<4"
cartopy = ">=0.25.0,<0.26"
pyproj = ">=3.7.2,<4"
sparse = ">=0.17.0,<0.18"
affine = ">=2.4.0,<3"
opt-einsum = ">=3.4.0,<4"

[pypi-dependencies]
legacy-converters = { path = ".", editable = true }
rasterix = ">=0.1a4"

[feature.dev.dependencies]
jupyterlab = "*"
jupyter-resource-usage = "*"
ruff-lsp = "*"
jedi-language-server = "*"
dask-labextension = "*"
jupyterlab_code_formatter = ">=3.0.2,<4"
black = ">=25.1.0,<26"
isort = ">=7.0.0,<8"
python = "3.13.*"

[feature.dev.tasks]
jupyterlab = { cmd = "jupyter lab", cwd = "." }

[feature.tests.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.tests.tasks]
tests = { cmd = "pytest --cov=legacy_converters", cwd = "." }

[feature.ci-py313.dependencies]
python = "3.13.*"

[feature.ci-py311.dependencies]
python = "3.11.*"

[environments]
dev = ["tests", "dev"]
ci-py311 = ["tests", "ci-py311"]
ci-py313 = ["tests", "ci-py313"]

[tasks.ci-py311]
depends-on = [{ task = "tests", environment = "ci-py311" }]

[tasks.ci-py313]
depends-on = [{ task = "tests", environment = "ci-py313" }]

[tasks.ci]
depends-on = [{ task = "tests", environment = "dev" }]
